/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#071e27",
        "tertiary-fixed": "#fbe0a5",
        "primary-container": "#064e3b",
        "secondary-container": "#cfe6f2",
        "surface-container": "#efeeea",
        "secondary-fixed-dim": "#b4cad6",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-background": "#1b1c1a",
        "primary": "#003527",
        "background": "#fbf9f5",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0b513d",
        "outline": "#707974",
        "surface-tint": "#2b6954",
        "on-secondary-container": "#526772",
        "on-tertiary-container": "#c8af78",
        "surface-variant": "#e4e2de",
        "on-surface": "#1b1c1a",
        "secondary-fixed": "#cfe6f2",
        "on-tertiary-fixed": "#251a00",
        "tertiary-container": "#534216",
        "inverse-on-surface": "#f2f0ed",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404944",
        "on-secondary-fixed-variant": "#354a53",
        "on-tertiary-fixed-variant": "#564418",
        "surface-container-highest": "#e4e2de",
        "on-primary-fixed": "#002117",
        "surface-dim": "#dbdad6",
        "inverse-surface": "#30312e",
        "primary-fixed": "#b0f0d6",
        "tertiary-fixed-dim": "#dec48b",
        "on-primary-container": "#80bea6",
        "surface": "#fbf9f5",
        "tertiary": "#3b2c02",
        "error": "#ba1a1a",
        "secondary": "#4c616c",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#95d3ba",
        "surface-container-low": "#f5f3ef",
        "surface-bright": "#fbf9f5",
        "outline-variant": "#bfc9c3",
        "surface-container-high": "#eae8e4",
        "inverse-primary": "#95d3ba",
      },
      fontFamily: {
        headline: ["NotoSerif_400Regular", "NotoSerif_700Bold"],
        body: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold"],
        label: ["Inter_400Regular", "Inter_500Medium"],
      },
    },
  },
  plugins: [],
};
