export const PRAYER_TIME_CALCULATOR = Symbol("PRAYER_TIME_CALCULATOR");
export const QIBLA_CALCULATOR = Symbol("QIBLA_CALCULATOR");
export const MOBILE_SYNC_SERVICE = Symbol("MOBILE_SYNC_SERVICE");
export const NOTIFICATION_DEVICE_REGISTRY = Symbol(
  "NOTIFICATION_DEVICE_REGISTRY",
);
export const NOTIFICATION_QUEUE = Symbol("NOTIFICATION_QUEUE");
export const PUSH_NOTIFICATION_SERVICE = Symbol("PUSH_NOTIFICATION_SERVICE");
